//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelesConflict {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VelesConflict.LocalizationData", typeof(LocalizationData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Points.
        /// </summary>
        internal static string AvailablePoints {
            get {
                return ResourceManager.GetString("AvailablePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        internal static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                          Error! You need an internet connection in order to play online..
        /// </summary>
        internal static string ConnectionRequired {
            get {
                return ResourceManager.GetString("ConnectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string DifficultyEasy {
            get {
                return ResourceManager.GetString("DifficultyEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string DifficultyHard {
            get {
                return ResourceManager.GetString("DifficultyHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insane.
        /// </summary>
        internal static string DifficultyInsane {
            get {
                return ResourceManager.GetString("DifficultyInsane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string DifficultyMedium {
            get {
                return ResourceManager.GetString("DifficultyMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Found.
        /// </summary>
        internal static string GameFound {
            get {
                return ResourceManager.GetString("GameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost, try again..
        /// </summary>
        internal static string GG {
            get {
                return ResourceManager.GetString("GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for games.
        /// </summary>
        internal static string LookingForGames {
            get {
                return ResourceManager.GetString("LookingForGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string Multiplayer {
            get {
                return ResourceManager.GetString("Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Match.
        /// </summary>
        internal static string QuickMatch {
            get {
                return ResourceManager.GetString("QuickMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        internal static string Research {
            get {
                return ResourceManager.GetString("Research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase growth
        ///
        ///
        ///
        ///
        ///
        ///With latest inventions in genetic engineering you can easily increase planet growth!
        ///
        ///	LightGreen	+10%	White	 for planet growth
        ///
        ///Price: {0}.
        /// </summary>
        internal static string Science1 {
            get {
                return ResourceManager.GetString("Science1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase speed
        ///
        ///
        ///
        ///
        ///
        ///Newest research in ship building will allow to boost your ship speed!
        ///
        ///	LightGreen	+7%	White	 to ship speed
        ///
        ///Price: {0}.
        /// </summary>
        internal static string Science2 {
            get {
                return ResourceManager.GetString("Science2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase attack
        ///
        ///
        ///
        ///
        ///
        ///Putting new guns will provide a boost to your attack powers!
        ///
        ///	LightGreen	+8%	White	 to attack
        ///
        ///Price: {0}.
        /// </summary>
        internal static string Science3 {
            get {
                return ResourceManager.GetString("Science3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase armor
        ///
        ///
        ///
        ///
        ///
        ///Your scientists have achieved unprecedented strength in the new metals, which significantly increases your armor!
        ///
        ///	LightGreen	+10%	White	 to armor
        ///
        ///Price: {0}.
        /// </summary>
        internal static string Science4 {
            get {
                return ResourceManager.GetString("Science4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out this cool Windows Phone 7 game!.
        /// </summary>
        internal static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the right you see the info screen.
        ///It will display the information about the episode and the updates in the update mode
        ///Tap to continue.
        /// </summary>
        internal static string Tutorial0 {
            get {
                return ResourceManager.GetString("Tutorial0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the center is the strategic screen, here you can move around
        ///and select the episode that you&apos;d like to play.
        ///The yellow one is the most current episode.
        ///Tap to continue.
        /// </summary>
        internal static string Tutorial1 {
            get {
                return ResourceManager.GetString("Tutorial1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By dragging the DNA icon to the bottom of the left corner you will access the update mode
        ///Do that now.
        ///Tap to continue.
        /// </summary>
        internal static string Tutorial2 {
            get {
                return ResourceManager.GetString("Tutorial2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this menu you can spend your science points on upgrades.
        ///To exit from this mode, drag the DNA icon back to its original position
        ///Tap to continue.
        /// </summary>
        internal static string Tutorial3 {
            get {
                return ResourceManager.GetString("Tutorial3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the mission screen, here you can select the mission on which you want to play
        ///Tap to continue.
        /// </summary>
        internal static string Tutorial4 {
            get {
                return ResourceManager.GetString("Tutorial4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you see three planets, the green is yours, the red is the enemy&apos;s. Those with no color are neutral.
        ///To attack a planet, select your planets by draging or tapping, and then double click the target
        ///Tap to continue.
        /// </summary>
        internal static string Tutorial5 {
            get {
                return ResourceManager.GetString("Tutorial5", resourceCulture);
            }
        }
    }
}
