//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace NewsAgent.VelesConflictReporting {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameUsageStastics", Namespace="http://schemas.datacontract.org/2004/07/VelesConflictDataReporting")]
    public partial class GameUsageStastics : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ActionsField;
        
        private string DeviceIDField;
        
        private int DifficultyField;
        
        private string MapField;
        
        private System.TimeSpan TimeSpentField;
        
        private int WinnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Actions {
            get {
                return this.ActionsField;
            }
            set {
                if ((this.ActionsField.Equals(value) != true)) {
                    this.ActionsField = value;
                    this.RaisePropertyChanged("Actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Difficulty {
            get {
                return this.DifficultyField;
            }
            set {
                if ((this.DifficultyField.Equals(value) != true)) {
                    this.DifficultyField = value;
                    this.RaisePropertyChanged("Difficulty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Map {
            get {
                return this.MapField;
            }
            set {
                if ((object.ReferenceEquals(this.MapField, value) != true)) {
                    this.MapField = value;
                    this.RaisePropertyChanged("Map");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeSpent {
            get {
                return this.TimeSpentField;
            }
            set {
                if ((this.TimeSpentField.Equals(value) != true)) {
                    this.TimeSpentField = value;
                    this.RaisePropertyChanged("TimeSpent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((this.WinnerField.Equals(value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuUsageStatistic", Namespace="http://schemas.datacontract.org/2004/07/VelesConflictDataReporting")]
    public partial class MenuUsageStatistic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ActionsField;
        
        private string DeviceIDField;
        
        private string MenuField;
        
        private System.TimeSpan TimeSpentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Actions {
            get {
                return this.ActionsField;
            }
            set {
                if ((this.ActionsField.Equals(value) != true)) {
                    this.ActionsField = value;
                    this.RaisePropertyChanged("Actions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Menu {
            get {
                return this.MenuField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuField, value) != true)) {
                    this.MenuField = value;
                    this.RaisePropertyChanged("Menu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan TimeSpent {
            get {
                return this.TimeSpentField;
            }
            set {
                if ((this.TimeSpentField.Equals(value) != true)) {
                    this.TimeSpentField = value;
                    this.RaisePropertyChanged("TimeSpent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelesConflictReporting.IReportingService")]
    public interface IReportingService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReportingService/RegisterDevice", ReplyAction="http://tempuri.org/IReportingService/RegisterDeviceResponse")]
        System.IAsyncResult BeginRegisterDevice(string DeviceID, System.AsyncCallback callback, object asyncState);
        
        void EndRegisterDevice(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReportingService/AddGameUsageStastics", ReplyAction="http://tempuri.org/IReportingService/AddGameUsageStasticsResponse")]
        System.IAsyncResult BeginAddGameUsageStastics(NewsAgent.VelesConflictReporting.GameUsageStastics stats, System.AsyncCallback callback, object asyncState);
        
        void EndAddGameUsageStastics(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReportingService/AddMenuUsageStastics", ReplyAction="http://tempuri.org/IReportingService/AddMenuUsageStasticsResponse")]
        System.IAsyncResult BeginAddMenuUsageStastics(NewsAgent.VelesConflictReporting.MenuUsageStatistic stats, System.AsyncCallback callback, object asyncState);
        
        void EndAddMenuUsageStastics(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReportingService/AddBatchMenuUsageStastics", ReplyAction="http://tempuri.org/IReportingService/AddBatchMenuUsageStasticsResponse")]
        System.IAsyncResult BeginAddBatchMenuUsageStastics(NewsAgent.VelesConflictReporting.MenuUsageStatistic[] stats, System.AsyncCallback callback, object asyncState);
        
        void EndAddBatchMenuUsageStastics(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReportingService/AddBatchGameUsageStastics", ReplyAction="http://tempuri.org/IReportingService/AddBatchGameUsageStasticsResponse")]
        System.IAsyncResult BeginAddBatchGameUsageStastics(NewsAgent.VelesConflictReporting.GameUsageStastics[] stats, System.AsyncCallback callback, object asyncState);
        
        void EndAddBatchGameUsageStastics(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IReportingService/GetLatestNews", ReplyAction="http://tempuri.org/IReportingService/GetLatestNewsResponse")]
        System.IAsyncResult BeginGetLatestNews(string locale, System.AsyncCallback callback, object asyncState);
        
        string EndGetLatestNews(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportingServiceChannel : NewsAgent.VelesConflictReporting.IReportingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLatestNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLatestNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportingServiceClient : System.ServiceModel.ClientBase<NewsAgent.VelesConflictReporting.IReportingService>, NewsAgent.VelesConflictReporting.IReportingService {
        
        private BeginOperationDelegate onBeginRegisterDeviceDelegate;
        
        private EndOperationDelegate onEndRegisterDeviceDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterDeviceCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddGameUsageStasticsDelegate;
        
        private EndOperationDelegate onEndAddGameUsageStasticsDelegate;
        
        private System.Threading.SendOrPostCallback onAddGameUsageStasticsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddMenuUsageStasticsDelegate;
        
        private EndOperationDelegate onEndAddMenuUsageStasticsDelegate;
        
        private System.Threading.SendOrPostCallback onAddMenuUsageStasticsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddBatchMenuUsageStasticsDelegate;
        
        private EndOperationDelegate onEndAddBatchMenuUsageStasticsDelegate;
        
        private System.Threading.SendOrPostCallback onAddBatchMenuUsageStasticsCompletedDelegate;
        
        private BeginOperationDelegate onBeginAddBatchGameUsageStasticsDelegate;
        
        private EndOperationDelegate onEndAddBatchGameUsageStasticsDelegate;
        
        private System.Threading.SendOrPostCallback onAddBatchGameUsageStasticsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLatestNewsDelegate;
        
        private EndOperationDelegate onEndGetLatestNewsDelegate;
        
        private System.Threading.SendOrPostCallback onGetLatestNewsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ReportingServiceClient() {
        }
        
        public ReportingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RegisterDeviceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddGameUsageStasticsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddMenuUsageStasticsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddBatchMenuUsageStasticsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddBatchGameUsageStasticsCompleted;
        
        public event System.EventHandler<GetLatestNewsCompletedEventArgs> GetLatestNewsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NewsAgent.VelesConflictReporting.IReportingService.BeginRegisterDevice(string DeviceID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterDevice(DeviceID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NewsAgent.VelesConflictReporting.IReportingService.EndRegisterDevice(System.IAsyncResult result) {
            base.Channel.EndRegisterDevice(result);
        }
        
        private System.IAsyncResult OnBeginRegisterDevice(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string DeviceID = ((string)(inValues[0]));
            return ((NewsAgent.VelesConflictReporting.IReportingService)(this)).BeginRegisterDevice(DeviceID, callback, asyncState);
        }
        
        private object[] OnEndRegisterDevice(System.IAsyncResult result) {
            ((NewsAgent.VelesConflictReporting.IReportingService)(this)).EndRegisterDevice(result);
            return null;
        }
        
        private void OnRegisterDeviceCompleted(object state) {
            if ((this.RegisterDeviceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterDeviceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterDeviceAsync(string DeviceID) {
            this.RegisterDeviceAsync(DeviceID, null);
        }
        
        public void RegisterDeviceAsync(string DeviceID, object userState) {
            if ((this.onBeginRegisterDeviceDelegate == null)) {
                this.onBeginRegisterDeviceDelegate = new BeginOperationDelegate(this.OnBeginRegisterDevice);
            }
            if ((this.onEndRegisterDeviceDelegate == null)) {
                this.onEndRegisterDeviceDelegate = new EndOperationDelegate(this.OnEndRegisterDevice);
            }
            if ((this.onRegisterDeviceCompletedDelegate == null)) {
                this.onRegisterDeviceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterDeviceCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDeviceDelegate, new object[] {
                        DeviceID}, this.onEndRegisterDeviceDelegate, this.onRegisterDeviceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NewsAgent.VelesConflictReporting.IReportingService.BeginAddGameUsageStastics(NewsAgent.VelesConflictReporting.GameUsageStastics stats, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddGameUsageStastics(stats, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NewsAgent.VelesConflictReporting.IReportingService.EndAddGameUsageStastics(System.IAsyncResult result) {
            base.Channel.EndAddGameUsageStastics(result);
        }
        
        private System.IAsyncResult OnBeginAddGameUsageStastics(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NewsAgent.VelesConflictReporting.GameUsageStastics stats = ((NewsAgent.VelesConflictReporting.GameUsageStastics)(inValues[0]));
            return ((NewsAgent.VelesConflictReporting.IReportingService)(this)).BeginAddGameUsageStastics(stats, callback, asyncState);
        }
        
        private object[] OnEndAddGameUsageStastics(System.IAsyncResult result) {
            ((NewsAgent.VelesConflictReporting.IReportingService)(this)).EndAddGameUsageStastics(result);
            return null;
        }
        
        private void OnAddGameUsageStasticsCompleted(object state) {
            if ((this.AddGameUsageStasticsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddGameUsageStasticsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddGameUsageStasticsAsync(NewsAgent.VelesConflictReporting.GameUsageStastics stats) {
            this.AddGameUsageStasticsAsync(stats, null);
        }
        
        public void AddGameUsageStasticsAsync(NewsAgent.VelesConflictReporting.GameUsageStastics stats, object userState) {
            if ((this.onBeginAddGameUsageStasticsDelegate == null)) {
                this.onBeginAddGameUsageStasticsDelegate = new BeginOperationDelegate(this.OnBeginAddGameUsageStastics);
            }
            if ((this.onEndAddGameUsageStasticsDelegate == null)) {
                this.onEndAddGameUsageStasticsDelegate = new EndOperationDelegate(this.OnEndAddGameUsageStastics);
            }
            if ((this.onAddGameUsageStasticsCompletedDelegate == null)) {
                this.onAddGameUsageStasticsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddGameUsageStasticsCompleted);
            }
            base.InvokeAsync(this.onBeginAddGameUsageStasticsDelegate, new object[] {
                        stats}, this.onEndAddGameUsageStasticsDelegate, this.onAddGameUsageStasticsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NewsAgent.VelesConflictReporting.IReportingService.BeginAddMenuUsageStastics(NewsAgent.VelesConflictReporting.MenuUsageStatistic stats, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddMenuUsageStastics(stats, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NewsAgent.VelesConflictReporting.IReportingService.EndAddMenuUsageStastics(System.IAsyncResult result) {
            base.Channel.EndAddMenuUsageStastics(result);
        }
        
        private System.IAsyncResult OnBeginAddMenuUsageStastics(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NewsAgent.VelesConflictReporting.MenuUsageStatistic stats = ((NewsAgent.VelesConflictReporting.MenuUsageStatistic)(inValues[0]));
            return ((NewsAgent.VelesConflictReporting.IReportingService)(this)).BeginAddMenuUsageStastics(stats, callback, asyncState);
        }
        
        private object[] OnEndAddMenuUsageStastics(System.IAsyncResult result) {
            ((NewsAgent.VelesConflictReporting.IReportingService)(this)).EndAddMenuUsageStastics(result);
            return null;
        }
        
        private void OnAddMenuUsageStasticsCompleted(object state) {
            if ((this.AddMenuUsageStasticsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddMenuUsageStasticsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddMenuUsageStasticsAsync(NewsAgent.VelesConflictReporting.MenuUsageStatistic stats) {
            this.AddMenuUsageStasticsAsync(stats, null);
        }
        
        public void AddMenuUsageStasticsAsync(NewsAgent.VelesConflictReporting.MenuUsageStatistic stats, object userState) {
            if ((this.onBeginAddMenuUsageStasticsDelegate == null)) {
                this.onBeginAddMenuUsageStasticsDelegate = new BeginOperationDelegate(this.OnBeginAddMenuUsageStastics);
            }
            if ((this.onEndAddMenuUsageStasticsDelegate == null)) {
                this.onEndAddMenuUsageStasticsDelegate = new EndOperationDelegate(this.OnEndAddMenuUsageStastics);
            }
            if ((this.onAddMenuUsageStasticsCompletedDelegate == null)) {
                this.onAddMenuUsageStasticsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddMenuUsageStasticsCompleted);
            }
            base.InvokeAsync(this.onBeginAddMenuUsageStasticsDelegate, new object[] {
                        stats}, this.onEndAddMenuUsageStasticsDelegate, this.onAddMenuUsageStasticsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NewsAgent.VelesConflictReporting.IReportingService.BeginAddBatchMenuUsageStastics(NewsAgent.VelesConflictReporting.MenuUsageStatistic[] stats, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddBatchMenuUsageStastics(stats, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NewsAgent.VelesConflictReporting.IReportingService.EndAddBatchMenuUsageStastics(System.IAsyncResult result) {
            base.Channel.EndAddBatchMenuUsageStastics(result);
        }
        
        private System.IAsyncResult OnBeginAddBatchMenuUsageStastics(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NewsAgent.VelesConflictReporting.MenuUsageStatistic[] stats = ((NewsAgent.VelesConflictReporting.MenuUsageStatistic[])(inValues[0]));
            return ((NewsAgent.VelesConflictReporting.IReportingService)(this)).BeginAddBatchMenuUsageStastics(stats, callback, asyncState);
        }
        
        private object[] OnEndAddBatchMenuUsageStastics(System.IAsyncResult result) {
            ((NewsAgent.VelesConflictReporting.IReportingService)(this)).EndAddBatchMenuUsageStastics(result);
            return null;
        }
        
        private void OnAddBatchMenuUsageStasticsCompleted(object state) {
            if ((this.AddBatchMenuUsageStasticsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddBatchMenuUsageStasticsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddBatchMenuUsageStasticsAsync(NewsAgent.VelesConflictReporting.MenuUsageStatistic[] stats) {
            this.AddBatchMenuUsageStasticsAsync(stats, null);
        }
        
        public void AddBatchMenuUsageStasticsAsync(NewsAgent.VelesConflictReporting.MenuUsageStatistic[] stats, object userState) {
            if ((this.onBeginAddBatchMenuUsageStasticsDelegate == null)) {
                this.onBeginAddBatchMenuUsageStasticsDelegate = new BeginOperationDelegate(this.OnBeginAddBatchMenuUsageStastics);
            }
            if ((this.onEndAddBatchMenuUsageStasticsDelegate == null)) {
                this.onEndAddBatchMenuUsageStasticsDelegate = new EndOperationDelegate(this.OnEndAddBatchMenuUsageStastics);
            }
            if ((this.onAddBatchMenuUsageStasticsCompletedDelegate == null)) {
                this.onAddBatchMenuUsageStasticsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddBatchMenuUsageStasticsCompleted);
            }
            base.InvokeAsync(this.onBeginAddBatchMenuUsageStasticsDelegate, new object[] {
                        stats}, this.onEndAddBatchMenuUsageStasticsDelegate, this.onAddBatchMenuUsageStasticsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NewsAgent.VelesConflictReporting.IReportingService.BeginAddBatchGameUsageStastics(NewsAgent.VelesConflictReporting.GameUsageStastics[] stats, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddBatchGameUsageStastics(stats, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void NewsAgent.VelesConflictReporting.IReportingService.EndAddBatchGameUsageStastics(System.IAsyncResult result) {
            base.Channel.EndAddBatchGameUsageStastics(result);
        }
        
        private System.IAsyncResult OnBeginAddBatchGameUsageStastics(object[] inValues, System.AsyncCallback callback, object asyncState) {
            NewsAgent.VelesConflictReporting.GameUsageStastics[] stats = ((NewsAgent.VelesConflictReporting.GameUsageStastics[])(inValues[0]));
            return ((NewsAgent.VelesConflictReporting.IReportingService)(this)).BeginAddBatchGameUsageStastics(stats, callback, asyncState);
        }
        
        private object[] OnEndAddBatchGameUsageStastics(System.IAsyncResult result) {
            ((NewsAgent.VelesConflictReporting.IReportingService)(this)).EndAddBatchGameUsageStastics(result);
            return null;
        }
        
        private void OnAddBatchGameUsageStasticsCompleted(object state) {
            if ((this.AddBatchGameUsageStasticsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddBatchGameUsageStasticsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddBatchGameUsageStasticsAsync(NewsAgent.VelesConflictReporting.GameUsageStastics[] stats) {
            this.AddBatchGameUsageStasticsAsync(stats, null);
        }
        
        public void AddBatchGameUsageStasticsAsync(NewsAgent.VelesConflictReporting.GameUsageStastics[] stats, object userState) {
            if ((this.onBeginAddBatchGameUsageStasticsDelegate == null)) {
                this.onBeginAddBatchGameUsageStasticsDelegate = new BeginOperationDelegate(this.OnBeginAddBatchGameUsageStastics);
            }
            if ((this.onEndAddBatchGameUsageStasticsDelegate == null)) {
                this.onEndAddBatchGameUsageStasticsDelegate = new EndOperationDelegate(this.OnEndAddBatchGameUsageStastics);
            }
            if ((this.onAddBatchGameUsageStasticsCompletedDelegate == null)) {
                this.onAddBatchGameUsageStasticsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddBatchGameUsageStasticsCompleted);
            }
            base.InvokeAsync(this.onBeginAddBatchGameUsageStasticsDelegate, new object[] {
                        stats}, this.onEndAddBatchGameUsageStasticsDelegate, this.onAddBatchGameUsageStasticsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult NewsAgent.VelesConflictReporting.IReportingService.BeginGetLatestNews(string locale, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLatestNews(locale, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string NewsAgent.VelesConflictReporting.IReportingService.EndGetLatestNews(System.IAsyncResult result) {
            return base.Channel.EndGetLatestNews(result);
        }
        
        private System.IAsyncResult OnBeginGetLatestNews(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string locale = ((string)(inValues[0]));
            return ((NewsAgent.VelesConflictReporting.IReportingService)(this)).BeginGetLatestNews(locale, callback, asyncState);
        }
        
        private object[] OnEndGetLatestNews(System.IAsyncResult result) {
            string retVal = ((NewsAgent.VelesConflictReporting.IReportingService)(this)).EndGetLatestNews(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLatestNewsCompleted(object state) {
            if ((this.GetLatestNewsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLatestNewsCompleted(this, new GetLatestNewsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLatestNewsAsync(string locale) {
            this.GetLatestNewsAsync(locale, null);
        }
        
        public void GetLatestNewsAsync(string locale, object userState) {
            if ((this.onBeginGetLatestNewsDelegate == null)) {
                this.onBeginGetLatestNewsDelegate = new BeginOperationDelegate(this.OnBeginGetLatestNews);
            }
            if ((this.onEndGetLatestNewsDelegate == null)) {
                this.onEndGetLatestNewsDelegate = new EndOperationDelegate(this.OnEndGetLatestNews);
            }
            if ((this.onGetLatestNewsCompletedDelegate == null)) {
                this.onGetLatestNewsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLatestNewsCompleted);
            }
            base.InvokeAsync(this.onBeginGetLatestNewsDelegate, new object[] {
                        locale}, this.onEndGetLatestNewsDelegate, this.onGetLatestNewsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override NewsAgent.VelesConflictReporting.IReportingService CreateChannel() {
            return new ReportingServiceClientChannel(this);
        }
        
        private class ReportingServiceClientChannel : ChannelBase<NewsAgent.VelesConflictReporting.IReportingService>, NewsAgent.VelesConflictReporting.IReportingService {
            
            public ReportingServiceClientChannel(System.ServiceModel.ClientBase<NewsAgent.VelesConflictReporting.IReportingService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegisterDevice(string DeviceID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = DeviceID;
                System.IAsyncResult _result = base.BeginInvoke("RegisterDevice", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRegisterDevice(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RegisterDevice", _args, result);
            }
            
            public System.IAsyncResult BeginAddGameUsageStastics(NewsAgent.VelesConflictReporting.GameUsageStastics stats, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = stats;
                System.IAsyncResult _result = base.BeginInvoke("AddGameUsageStastics", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddGameUsageStastics(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddGameUsageStastics", _args, result);
            }
            
            public System.IAsyncResult BeginAddMenuUsageStastics(NewsAgent.VelesConflictReporting.MenuUsageStatistic stats, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = stats;
                System.IAsyncResult _result = base.BeginInvoke("AddMenuUsageStastics", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddMenuUsageStastics(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddMenuUsageStastics", _args, result);
            }
            
            public System.IAsyncResult BeginAddBatchMenuUsageStastics(NewsAgent.VelesConflictReporting.MenuUsageStatistic[] stats, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = stats;
                System.IAsyncResult _result = base.BeginInvoke("AddBatchMenuUsageStastics", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddBatchMenuUsageStastics(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddBatchMenuUsageStastics", _args, result);
            }
            
            public System.IAsyncResult BeginAddBatchGameUsageStastics(NewsAgent.VelesConflictReporting.GameUsageStastics[] stats, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = stats;
                System.IAsyncResult _result = base.BeginInvoke("AddBatchGameUsageStastics", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddBatchGameUsageStastics(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddBatchGameUsageStastics", _args, result);
            }
            
            public System.IAsyncResult BeginGetLatestNews(string locale, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = locale;
                System.IAsyncResult _result = base.BeginInvoke("GetLatestNews", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetLatestNews(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetLatestNews", _args, result)));
                return _result;
            }
        }
    }
}
